# Generated by Django 3.2.8 on 2021-12-04 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('audio_file', models.FileField(upload_to='audio-recordings/', verbose_name='Audio File')),
                ('User', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
